sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: Iwb1BZ8cn5ksM9uY2XY9hIr12CMp1jDJYJwk9AljS+/z+JPZuWg38ZC9PivCGZ/ZEqgFgwGJ6bwnZLn3Y6Twxv0pkwNlqn3U+FkUIGz+JoAcxI1PnqR7R36kCoVfvF03XjqTFSb5ckyrK5/PafN8BgSK5E5u51kfxQ1NvUiRUC9Y4fm5fmNfOHjrCFbS4FvuoBXT4Uq+cJapGpzn1qZL9qqhHttOSafUjd9iWSGDiPAE0LhRlDLhjyoxXVYXhI0ru2ZFoZ3MsV4r2oBhLPhL2g8W+pTkxZPl/5yrsejgAppxV1TjiQ+DAa+62Cn8/7fV70K6v1IzbOn2vTq6DwgRBHP64MPfa7UkfQ1M5gJ28EeWo93BfSRSM8xhMWod7r318FiX9LpflUk6iX5VtZAF1BPvNE409fCuR2D3SUazDNt/vrwFWfWzNCe27WsNaVlBTaH8Dh16XmCrmPAE+IX2CG7eJpY6TCURO0lQiTH0MHiIt5IcUr/zVg9kIikNQIMn1VtBNDjM0ckZ6hX66ECNrXOXecN5xXN+baf0IdN88sbeAqZRulpRvpLnBMyGGQU4g5RuEpIuN6b/0EH1eE0hEUfxPRortmZJXXCqazlf+ttz+D4KUfHVaYvWxxr+wxkkGRqg6fe8iyTJKx5xEgS8uUMO5fYUVz496Z04km1ecTU=}, {secure: rb3NisHHOILyZctGwkWXZvfVFJdHHk2TvDVg/RfzCDRmYptlE1etIDGOW2oA5yU28E3aUa7kRqXZrfpApo1Nf1RMCqKUSpYXcgvJ6Ph+tpAHn5rk76TK2fY69plkp2zPuv8m8T3rTFc4zSRUWgm2G/Bp5UQeEfrONd8qkkqveXCTXwpn38YLh1g0qVSFhikvR3ukaGxXNTcTRABOjT6prae3pBI8QCsMoAg+zqaRWpBGJJjnXi3Lg9PNYSU8kxDnE8CgMEZHByJizfW+YhrBwRGlSz6tAwcFomUL63zCgE3INHpukA/9oPSzj5Go8oOJ4XPIh5SDAjCsLpBCHShTnx5X8lw0rKtPcs/a8gpNTzQQ1zstOF1L4++g9LU7rzKYfXz+jbVStV8YtCgvDZLSXeEEFTkpG3sWhjuY4usut/u/DgZweO6tlgiC3TVHrB32rCJpF8ryXZuUfWtNDyU+kT2KG7u8elq8opcnefOZWiLslqsTW6Nj5u4mGKbU95G/SgRLvTJhhXxH/LDV08mkV8pwTdsXygke7nwq/YbKSdv+rEnMKcAH5eyf9X01jg0IniuQuTkl72YBySOFBAbRhs6llCRsPH9lK2/fnZDCpxDq9RmvXH3SyaBTRDtKTNHKgLOI07nqsr6SgymB8FmPALQraiNzueuLWNPXisWu3/k=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
